# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.(IF I HAD ANY)
[rocks]

# List of Neovim plugins to install alongside their versions.
[plugins]
"rocks.nvim" = "2.45.2" # rocks.nvim can also manage itself :D
"rocks-git.nvim" = "2.5.5"
neorg = "9.3.0"
tree-sitter-cpp = "0.0.45"
tree-sitter-rust = "0.0.50"
"which-key.nvim" = "3.17.0"
nvim-web-devicons = "0.100"
tree-sitter = { git = "jacobdot/nvim-treesitter.nvim" }
"nvim-colorizer.lua" = { git = "norcalli/nvim-colorizer.lua" }
lspconfig = { git = "neovim/nvim-lspconfig" }
alpha = { git = "goolord/alpha-nvim" }
toggleterm = { git = "akinsho/toggleterm.nvim" }
noice = { git = "folke/noice.nvim" }
cozy-line-numbers = { git = "mluders/comfy-line-numbers.nvim" }
"diagflow.nvim" = { git = "dgagn/diagflow.nvim" }
"snacks.nvim" = { git = "folke/snacks.nvim" }
"mini.nvim" = { git = "echasnovski/mini.nvim" }
